#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: ImageMagick-7.0.1 ';
		echo 'AMH-ModuleDescription: 升级更新CVE-2016-3714号安全问题，安装路径为/usr/local/image_magick-7.0/bin当前版本为7.0.1。ImageMagick是一套功能强大、稳定而且开源的工具集和开发包，可以用来读、写和处理超过89种基本格式的图片文件，包括流行的TIFF、JPEG、GIF、 PNG、PDF以及PhotoCD等格式。 ';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2016-05-06';
		echo 'AMH-ModuleAdmin:';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleScriptBy: amysql';
		echo 'AMH-ModuleIco: http://amysql.com/View/images/amh_module/ImageMagick.gif';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
			exit;
		else
			cd /usr/local/;
			wget http://code.amysql.com/files/ImageMagick-7.0.1.tar.gz;
			tar -zxvf ImageMagick-7.0.1.tar.gz;
			cd ImageMagick-7.0.1/;
			./configure --prefix=/usr/local/imagemagick;
			make && make install;
			cd /usr/local/;
			rm -rf ImageMagick-7.0.1.tar.gz ImageMagick-7.0.1;

			wget http://pecl.php.net/get/imagick-3.4.1.tgz;
			tar zxvf imagick-3.4.1.tgz;
			cd imagick-3.4.1/;
			/usr/local/php/bin/phpize;
			./configure --with-php-config=/usr/local/php/bin/php-config --with-imagick=/usr/local/imagemagick;
			make && make install;
			cd /usr/local/;
			rm -rf imagick-3.4.1.tgz imagick-3.4.1;
			echo 'extension = "imagick.so"' >>/etc/php.ini;
			amh php reload;
 		 	amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
			echo '[OK] ImageMagick No management options.';
		else
			exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then
			rm -rf /usr/local/imagemagick/
			sed -i '/imagick.so/d' /etc/php.ini;
			amh php reload;
			echo '[OK] ImageMagick Uninstall successful.';
		else
			exit;
		fi;
}

#status
function amh_module_status()
{
		if [ -d "/usr/local/imagemagick" ]; then
			echo '[OK] ImageMagick is already installed.';
			return 0;
		else
			echo '[Notice] ImageMagick is not installed.';
			return 1;
		fi;
}
